### PR TITLE
Rename dahlem.html to dahlem-2.html

### PR DESCRIPTION
**Pull request by Justinborzi**
This should make your dahlem page look a little better and easier to read.

Issue for this pull request:   

**Problem to solve:**

**Solution chosen:**

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Hi @Justinborzi thanks for your pull-requets!
I see that you added a new page.

Would you also like to improve the Potsdam page and dahlem page?
If so, you can modify _layouts/overview.yml or the css file in the css directory.

**Comment by niccokunzmann** [comment]
I see: This is an html file.

We generate these files using jekyll.
If we could put the changes into the overview.html file in the _layouts folder and generate the site using jekyll, style changes will also be available for the Potsdam.html page.

**Comment by niccokunzmann** [comment]
You issue number would be #1

**Comment by niccokunzmann** [comment]
I had a look at it here: http://material.quelltext.eu/dahlem-2.html I like it. Would you like to change the css file to make at available for all dojos?

**Comment by niccokunzmann** [comment]
Here is how I think, your [styling](https://github.com/CoderDojoPotsdam/intro/pull/57/files#diff-79de78216cac2d10c210b263feeb0480R25) cen be integrated for all dojos:

- Put a div around [line 30 in overview.html](https://github.com/CoderDojoPotsdam/intro/blob/master/_layouts/overview.html#L30) with a class="top-language-structure"
- add this to the css file and add styling:
  ```
  .top-language-structure {
     /* put your styling here */
  }
  ```
This way, jekyll will generate the new site for all languages and add your styling to all elements with the 
`top-language-structure` class.

What do you think, would you like to try this?

**Comment by Justinborzi** [comment]
sorry for being unavailable, ive been busy, but yeah

**Pull request merged**
