### PR TITLE
added JavaScript Tutorials

### PR DESCRIPTION
**Pull request by bomholtm**
- JS Hero
- OpenTechSchool
- Khan Academy

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Wow, thanks!

**Comment by niccokunzmann** [comment]
We have a page build failure: https://travis-ci.org/CoderDojoPotsdam/intro/builds/285944307#L1118
Just telling you, would you like to work on it, if not, this is totally ok!

**Comment by bomholtm** [comment]
You’re welcome, I was happy to do it.

**Comment by niccokunzmann** [comment]
If you like to collaborate more on this, I invite you as a collaborator so you can accept other peoples pull-requests: https://github.com/CoderDojoPotsdam/intro/invitations

**Pull request merged**
