### PR TITLE
translate to English

### PR DESCRIPTION
**Pull request by niccokunzmann**
change German to English in English tag
@jccabrejas, you can merge :)

### CODE REVIEW

**Comment by niccokunzmann** [comment]
@jccabrejas I made a mistake. Do you have merge access now?

**Comment by jccabrejas** [comment]
it still says that I´m not authorized to merge this pull request. I was already wondering if I am too dumb to find a merge button somewhere ;-)

**Comment by niccokunzmann** [comment]
There should be a green merge button... I asked you to join the team intro. There should be a green merge button now. Can you show me what the page looks like for you? You can copy and paste a screen shot into the comment.

**Comment by jccabrejas** [comment]
image

**Comment by niccokunzmann** [comment]
You are in the team: https://github.com/orgs/CoderDojoPotsdam/teams/intro/members
And you should see this page: https://github.com/CoderDojoPotsdam/intro/settings/collaboration

**Pull request merged**
